language: java
env:
  - PLAY_VERSION=2.1.3
scala:
 - 2.10.2
before_script: 
 - wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
 - unzip -q play-${PLAY_VERSION}.zip 
script: play-${PLAY_VERSION}/play test
